version: "3.2"
services:

  # rs-sh1
  rs-01:
    image: mongo:4.4.4
    container_name: rs-01
    volumes:
      - rs-01:/data/db
    expose:
      - 27013
    ports:
      - 27013:27013
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27013", "--replSet", "rs-1", "--shardsvr" ]
  rs-02:
    image: mongo:4.4.4
    container_name: rs-02
    volumes:
      - rs-02:/data/db
    expose:
      - 27014
    ports:
      - 27014:27014
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27014", "--replSet", "rs-1", "--shardsvr" ]


  # rs-config
  rs-conf-01:
    image: mongo:4.4.4
    depends_on:
      - rs-02
    container_name: rs-conf-01
    volumes:
      - rs-conf-01:/data/configdb
    expose:
      - 27017
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27017", "--replSet", "rs-config", "--configsvr" ]
  rs-conf-02:
    image: mongo:4.4.4
    depends_on:
      - rs-02
    container_name: rs-conf-02
    volumes:
      - rs-conf-02:/data/configdb
    expose:
      - 27018
    ports:
      - 27018:27018
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27018", "--replSet", "rs-config", "--configsvr" ]

  # rs-mongos
  mongos:
    image: mongo:4.4.4
    container_name: mongos
    depends_on:
      - rs-conf-02
    expose:
      - 27020
    ports:
      - 27020:27020
    entrypoint: [ "/usr/bin/mongos", "--bind_ip_all", "--port", "27020", "--configdb", "rs-config/rs-conf-01:27017,rs-conf-02:27018" ]

  web:
    container_name: ci4-web
    image: codeigniter4:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - mongos

volumes:
  rs-01:
  rs-02:
  rs-conf-01:
  rs-conf-02: